import './globals.css'
import {NavigationProvider} from './context/nav'; 

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <NavigationProvider>
    <html lang="en" className="bg-black flex flex-col items-center justify-between">
      <body>
      {children}</body>
    </html>
    </NavigationProvider>
  )
}
